# Generated by Django 2.1.3 on 2018-12-01 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=10)),
                ('guest_c_id', models.CharField(max_length=18, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Guest', to_field='guest_c_id')),
            ],
        ),
        migrations.CreateModel(
            name='Reverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_date', models.DateField(default=datetime.date.today)),
                ('order_date', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Guest', to_field='guest_c_id')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_price', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'have been reserved'), ('2', 'have been lived in'), ('0', 'empty')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=1024)),
                ('user_password', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Room_type'),
        ),
        migrations.AddField(
            model_name='reverse',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Room', to_field='room_number'),
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Room', to_field='room_number'),
        ),
    ]
