# Generated by Django 2.1.3 on 2018-12-01 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reverse',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reverse',
            name='room',
        ),
        migrations.AddField(
            model_name='order',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reverse_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Reverse',
        ),
    ]
