# Generated by Django 2.1.3 on 2018-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manage', '0002_auto_20181201_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('1', 'have been reserved'), ('2', 'have been lived in'), ('0', 'empty')], default='0', max_length=2),
        ),
    ]
