# Generated by Django 2.1.3 on 2018-12-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_manage', '0003_auto_20181204_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Guest'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_manage.Room'),
        ),
    ]
